---
- name: AddLineAndREgistry - TEST
  hosts: all
  gather_facts: yes
  tasks:

  - name: Hello World! {{ my_variable }}
    win_shell: echo "Hi! '{{ my_variable }}'"

  - name: Create file if it doesn't exist with a specific encoding
    win_lineinfile:
      path: C:\temp\utf16-2.txt
      create: yes
      encoding: utf-16
      line: This is a utf-16 encoded file

  #- name: Read file to fact
  #  set_fact:
  #    file_text: "{{ lookup('file', 'C:\\temp\\utf16-2.txt') }}"
      
  - name: Read from file
    win_shell: cat C:\temp\utf16-2.txt
    register: file_contents

  - name: Tasks
    debug:
      msg: "success"
    when: '"This" in file_contents.stdout'
        
  #- name: Show content from file
  #  debug:
  #    msg: |
  #      "{{ file_text }}"

  - name: Find files in path
    win_find:
      paths: C:\temp
 
  - name: Add line to file test
    win_lineinfile:
      path: C:\temp\MyFile2.txt
      line: |
        This is my text
        ""
      insertafter: EOF
        
  # HKCU means HKEY_CURRENT_USER
  - name: Add or update registry path MyCompany, with dword entry 'hello', and containing 0xff2500ae as the hex value
    win_regedit:
      path: HKCU:\Software\MyCompany
      name: hello
      data: 0xff2500ae
      type: dword
