---
- name: Hello World!
  hosts: all

  tasks:
    - name: Register loop output as a variable
      ansible.builtin.shell: "echo {{ item }}"
      loop:
        - "one"
        - "two"
      register: echo
      
    - name: Print output
      debug:
        msg: "Echo output: {{ echo.results[0].end }}"
