---
- name: Merge two lists of dictionaries/objects - By Chris Vickers 
  hosts: all
  vars:
    names:
      - id: 1
        name: First name
      - id: 2
        name: Second name
    ages:
      - id: 1
        age: 10
      - id: 2
        age: 20

  tasks:

  - name: Start
    debug: msg="Start dictonary merge playbook"

  - name: Combine      
    set_fact:
      dict_combined: >-
        {{ dict_combined | default([])
           + [item | combine(age_item)]
        }} 
    vars:
      age_item: >-
        {{ ages
          | selectattr('id','equalto',item['id'])
          | list
          | first
        }}
    loop: "{{ names }}"
    
  - name: Output
    debug: msg="Merged dictionary':' '{{ dict_combined }}'"
