---
- name: Show value of whoami v2
  hosts: all
  tasks:
    - name: Save the result of 'whoami' in 'whoami_out'
      win_command: whoami
      register: whoami_out
   
    - name: Print output
      debug:
        msg: "whoami output: {{ whoami_out.stdout_lines[0] }}"
