---
- name: Windows Update Registry
  hosts: all
  gather_facts: yes
  tasks:
        
  # HKCU means HKEY_CURRENT_USER
  - name: Update registry value
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\Winstations\RDP-Tcp
      name: UserAuthentication
      data: 1
      type: dword

  # HKCU means HKEY_CURRENT_USER
  - name: Update registry value
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\Winstations\RDP-Tcp
      name: MinEncryptionLevel
      data: 1
      type: dword
